### ISSUE TITLE
Is their any way to connect QB without click update status or set autorun the QB webconnector?

### ISSUE THREAD

**Issue by ashwin-raj** [fedyunin/qbwcpoc#5]
Is their any way to connect QB without click update status or set autorun the QB web connector?

**Comment by fedyunin** [comment]
Probably no. The QB webconnector is app that consume your webservice. You can setup Scheduler section in your QWC file (See details on page 37 here: https://developer-static.intuit.com/qbSDK-current/doc/PDF/QBWC_proguide.pdf). Or end user can setup this by activate Autorun option in QB webconnector for your service. 

"Your end user can specify the update interval in the QB web 
connector UI. You can optionally supply a default update interval by 
including the <Scheduler> aggregate, but be aware that the user 
can override your settings in the UI." - from https://developer-static.intuit.com/qbSDK-current/doc/PDF/QBWC_proguide.pdf

**Comment by ashwin-raj** [comment]
Thanks
